// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id int64 `path:"id"`
}

type UserDetails struct {
	Name     string  `json:"name"`
	Age      int32   `json:"age"`
	Semester int32   `json:"semester"`
	CGPA     float64 `json:"cgpa"`
}
