// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ahsan-n/go-zero-webapp/webapp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getUserDetails/:id",
				Handler: getUserDetailsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
